# Configuration for Alacritty, the GPU enhanced terminal emulator.

font:
  size: 12.0

colors:
  primary:
   background: '#212121'
   foreground: '#ECEFF1'

  cursor:
    text: CellBackground
    cursor: '#B0BEC5'

  normal:
    black:   '#546E7A'
    red:     '#FF5252'
    green:   '#5CF19E'
    yellow:  '#FFD740'
    blue:    '#40C4FF'
    magenta: '#FF4081'
    cyan:    '#64FCDA'
    white:   '#ECEFF1'

  bright:
    black:   '#B0BEC5'
    red:     '#FF8A80'
    green:   '#B9F6CA'
    yellow:  '#FFE57F'
    blue:    '#80D8FF'
    magenta: '#FF80AB'
    cyan:    '#A7FDEB'
    white:   '#FFFFFF'
