#!/bin/sh

## Howto's/cheatsheets
alias \
  how-to-ubuntu-arm-grub="echo                                                                                          '\
                         \n  #============================ conflicts files ==========================================#   \
                         \n  mv /boot/firmware /boot/efi                                                                 \
                         \n  mv /boot/efi/boot.scr /boot/efi/boot.scr.bak                                                \
                         \n  mv /boot/efi/config.txt /boot/efi/config.txt.bak                                            \
                         \n  mv /boot/efi/cmdline.txt /boot/efi/cmdline.txt.bak                                          \
                         \n                                                                                              \
                         \n  #============================ installing grub ==========================================#   \
                         \n  #cp /usr/lib/u-boot/rpi_4/u-boot.bin /boot/efi/kernel8.img                                  \
                         \n  cp /ArchLinuxARM/boot/efi/kernel8.img /boot/efi/kernel8.img                                 \
                         \n  apt install grub-efi-arm64                                                                  \
                         \n  grub-install --no-nvram                                                                     \
                         \n  update-grub                                                                                 \
                         \n  #press ctrl-c many times to enter to grub if get stack at boot                              \
                         \n                                                                                              \'" \
  how-to-manjaro-arm-grub="echo                                                                                         '\
                         \n  #============================ conflicts files ==========================================#   \
                         \n  mv /boot/config.txt /boot/config.txt.bak                                                    \
                         \n  pacman -Syu linux uboot-raspberrypi uboot-tools grub efibootmgr os-prober                   \
                         \n  mv /boot/extlinux /boot/extlinux.bak                                                        \
                         \n                                                                                              \
                         \n  #======================== generating booting script ====================================#   \
                         \n  sed -i 's/UUID=<olduuid>/UUID=<newuuid>/g' root/etc/fstab                                   \
                         \n  sed -i 's/UUID=<olduuid>/UUID=<newuuid>/g' /boot/cmdline.txt                                \
                         \n  cp /ArchlinuxARM/boot/{boot.txt,mkscr} /boot                                                \
                         \n  cd /boot && ./mkscr                                                                         \
                         \n                                                                                              \
                         \n  #============================ installing grub ==========================================#   \
                         \n  cp /boot/Image /boot/vmlinuz-linux                                                          \
                         \n  grub-install --target=arm64-efi --efi-directory=/boot --bootloader-id=GRUB --removable      \
                         \n  grub-install --target=arm64-efi --efi-directory=/boot --bootloader-id=GRUB --no-nvram       \
                         \n  echo 'GRUB_DISABLE_OS_PROBER=false' >> /etc/default/grub                                    \
                         \n  grub-mkconfig -o /boot/grub/grub.cfg                                                        \
                         \n                                                                                              \'" \
  how-to-manjaro-arm-grub-efi="echo                                                                                     '\
                         \n  #============================ conflicts files ==========================================#   \
                         \n  mv /boot/config.txt /boot/config.txt.bak                                                    \
                         \n  pacman -Syu linux uboot-raspberrypi uboot-tools grub efibootmgr os-prober                    \
                         \n  mv /boot/extlinux /boot/extlinux.bak                                                        \
                         \n                                                                                              \
                         \n  #============================ mounting efi =============================================#   \
                         \n  mkdir /boot/efi                                                                             \
                         \n  sed -i 's|boot|boot/efi|g' /root/etc/fstab                                                  \
                         \n  reboot                                                                                      \
                         \n                                                                                              \
                         \n  #============================ installing grub ==========================================#   \
                         \n  cp /boot/efi/Image /boot/efi/vmlinuz-linux                                                  \
                         \n  grub-install --no-nvram                                                                     \
                         \n  echo 'GRUB_DISABLE_OS_PROBER=false' >> /etc/default/grub                                    \
                         \n  grub-mkconfig -o /boot/grub/grub.cfg                                                        \
                         \n                                                                                              \'" \
  how-to-arch-arm-grub="echo                                                                                            '\
                         \n  #========================= creating booting script =====================================#   \
                         \n  # replace/add to boot.txt                                                                   \
                         \n  if load ${devtype} ${devnum}:${bootpart} ${kernel_addr_r} /EFI/GRUB/grubaa64.efi; then      \
                         \n    if load ${devtype} ${devnum}:${bootpart} ${fdt_addr_r} /dtbs/${fdtfile}; then             \
                         \n      bootefi ${kernel_addr_r} ${fdt_addr_r};                                                 \
                         \n    fi;                                                                                       \
                         \n  fi                                                                                          \
                         \n  cd /boot && ./mkscr                                                                         \
                         \n                                                                                              \
                         \n  #============================ setting usb boot =========================================#   \
                         \n  sed -i 's/mmcblk0/UUID=<uuid>/g' root/etc/fstab                                             \
                         \n  sed -i 's/MODULES=()/MODULES=(pcie_brcmstb)/g' /etc/mkinitcpio.conf                         \
                         \n  mkinitcpio -P                                                                               \
                         \n  echo '%wheel ALL=(ALL) ALL' > /etc/sudoers.d/wheel                                          \
                         \n                                                                                              \
                         \n  #============================ installing grub ==========================================#   \
                         \n  pacman -Syu uboot-tools grub efibootmgr os-prober                                           \
                         \n  cp /boot/Image /boot/vmlinuz-linux                                                          \
                         \n  # to create /boot/efi/BOOT/bootaa64.efi                                                     \
                         \n  grub-install --target=arm64-efi --efi-directory=/boot --bootloader-id=BOOT --removable      \
                         \n  # to create /boot/efi/GRUB/grubaa64.efi                                                     \
                         \n  grub-install --target=arm64-efi --efi-directory=/boot --bootloader-id=GRUB --no-nvram       \
                         \n  echo 'GRUB_DISABLE_OS_PROBER=false' >> /etc/default/grub                                    \
                         \n  grub-mkconfig -o /boot/grub/grub.cfg                                                        \
                         \n                                                                                              \'" \
