#!/bin/bash

# change the desktop number here
FLOATING_DESKTOP_ID=$(bspc query -D -d '^9')
FLOATING_DESKTOP_ID2=$(bspc query -D -d '^10')

bspc subscribe node_add | while read -a msg ; do
   echo "node_add: ${msg[@]}"
   desk_id=${msg[2]}
   wid=${msg[4]}
   [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating  &&  bspc config -d $FLOATING_DESKTOP_ID border_width 1 && bspc config -d $FLOATING_DESKTOP_ID window_gap 0
   [ "$FLOATING_DESKTOP_ID2" = "$desk_id" ] && bspc node "$wid" -t floating  &&  bspc config -d $FLOATING_DESKTOP_ID2 border_width 1 && bspc config -d $FLOATING_DESKTOP_ID2 window_gap 0
   # [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc rule -a \* -o state=floating
   # [ "$FLOATING_DESKTOP_ID2" = "$desk_id" ] && bspc rule -a \* -o state=floating
done

