#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
# pgrep bspswallow || $HOME/.config/bspwm/bspswallow &
# remaps &

bsp-layout set rtall VII --master-size 0.8 &
bsp-layout set rtall VIII --master-size 0.8 &
$HOME/.config/bspwm/bspfloatdesk &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
# bspc config window_gap          8

# bspc config split_ratio          0.52
bspc config split_ratio          0.4
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          -5
bspc config bottom_padding       0
# bspc config top_padding          -9
# bspc config bottom_padding       -4
# bspc config top_padding          -5
# bspc config bottom_padding       -1

# bspc config normal_border_color	"#4c566a"
# bspc config active_border_color	"#1e1e1e"
# bspc config focused_border_color "#327bd1"
# bspc config presel_feedback_color	"#327bd1"
bspc config presel_feedback_color	"#4c566a"
# bspc config urgent_border_color "#dd2727"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
